---
title: "resultado_analise_descritiva"
output: html_document
---

Muitos pacientes não tiveram classificação do estado no seu registro, então temos BR como um estado para agrupar esses dados. Nas analises de totais por estado e municipio esses dados ficarão distorcidos.

"Dimensões do dataset:"
100672      5

"Colunas:"
"semEpi"       "estadoIBGE"   "municipio"    "faixa_etaria" "casos"

Total geral de casos: 597743 

Total de casos para 70 anos e mais (nacional): 62736

=== Total e percentual de casos por estado ===
 estadoIBGE total_casos   perc
   <chr>            <dbl>  <dbl>
 1 BR              298853 0.500 
 2 SP              109672 0.183 
 3 MG               19648 0.0329
 4 RJ               18989 0.0318
 5 GO               18205 0.0305
 6 PA               12523 0.0210
 7 SC               11073 0.0185
 8 RO               10859 0.0182
 9 AM                9739 0.0163
10 RS                9579 0.0160


=== Top 10 municípios com mais casos ===
municipio           total_casos    perc
   <chr>                     <dbl>   <dbl>
 1 NA                       298853 0.500  
 2 SAO PAULO                 25960 0.0434 
 3 RIO DE JANEIRO            12799 0.0214 
 4 BRASILIA                   4138 0.00692
 5 BOTUCATU                   3871 0.00648
 6 MANAUS                     3762 0.00629
 7 GOIANIA                    3299 0.00552
 8 PORTO VELHO                3080 0.00515
 9 SAO JOSE DOS CAMPOS        3054 0.00511
10 CAMPINAS                   2796 0.00468

=== Total e percentual de casos por faixa etária ===
faixa_etaria      total_casos    perc
   <chr>                   <dbl>   <dbl>
 1 20 a 39 anos           197054 0.330  
 2 40 a 59 anos           175087 0.293  
 3 70 anos e mais          62736 0.105  
 4 60 a 69 anos            59660 0.0998 
 5 16 a 19 anos            24209 0.0405 
 6 11 a 15 anos            20462 0.0342 
 7 05 a 10 anos            19732 0.0330 
 8 07 meses a 01 ano       13878 0.0232 
 9 02 a 04 anos            10665 0.0178 
10 0 a 06 meses             8348 0.0140 
11 sem informaç             5912 0.00989

=== Total de casos em idosos 70+ por estado ===
estadoIBGE total_casos n_pacientes media_casos_por_paciente perc_nacional perc_pacientes
   <chr>            <dbl>       <int>                    <dbl>         <dbl>          <dbl>
 1 BR               31364          37                   848.           50.0            0.3 
 2 SP               13422        3686                     3.64         21.4           29.8 
 3 MG                2465        1365                     1.81          3.93          11.0 
 4 RJ                2025         470                     4.31          3.23           3.8 
 5 GO                1694         850                     1.99          2.7            6.88
 6 RS                1313         789                     1.66          2.09           6.38
 7 SC                 923         545                     1.69          1.47           4.41
 8 PA                 889         472                     1.88          1.42           3.82
 9 PE                 852         460                     1.85          1.36           3.72
10 CE                 846         473                     1.79          1.35           3.83
